language: c

os:
- linux
- osx

compiler: gcc

before_install: 
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install pandoc; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install pandoc; fi
- cd src

script:
- make
- make test
