language: c

os:
- linux
- osx
- freebsd

compiler: gcc

matrix:
  include:
    -os: linux
    addons:
      apt:
        packages:
          - pandoc
    -os: osx
    addons:
      homebrew:
        packages:
          - pandoc
    -os: freebsd
    addons:
      pkg:
        - hs-pandoc

script:
- cd src
- if [ "$TRAVIS_OS_NAME" = "freebsd" ]; then gmake; fi
- if [ "$TRAVIS_OS_NAME" != "freebsd" ]; then make; fi
- make test
