language: c

os:
- linux
- osx
- freebsd

addons:
  apt:
    packages: 
      - pandoc
  homebrew:
    packages:
      - pandoc
  pkg:
      - pandoc

compiler: gcc

before_install: 
- cd src

script:
- make
- make test
