language: c

os:
  - linux
  - osx
  - freebsd

addons:
  apt:
    packages:
      - pandoc
  homebrew:
    packages:
      - pandoc
compiler: gcc

script:
- cd src
- if [ "$TRAVIS_OS_NAME" = "freebsd" ]; then pkg install hs-pandoc; fi
- if [ "$TRAVIS_OS_NAME" = "freebsd" ]; then gmake; fi
- if [ "$TRAVIS_OS_NAME" != "freebsd" ]; then make; fi
- make test
