language: c

os:
  - linux
  - osx
  - freebsd

addons:
  apt:
    packages:
      - pandoc
  homebrew:
    packages:
      - pandoc
compiler: gcc

script:
- if [ "$TRAVIS_OS_NAME" = "freebsd" ]; then echo "IGNORE_OSVERSION=yes" >> /etc/rc.conf; fi
- if [ "$TRAVIS_OS_NAME" = "freebsd" ]; then sudo pkg update; fi
- if [ "$TRAVIS_OS_NAME" = "freebsd" ]; then sudo pkg install hs-pandoc; fi
- cd src
- if [ "$TRAVIS_OS_NAME" = "freebsd" ]; then gmake; fi
- if [ "$TRAVIS_OS_NAME" != "freebsd" ]; then make; fi
- make test
