language: c

jobs:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - pandoc
    - os: osx
      addons:
        brew:
          packages:
            - pandoc
    - os: freebsd
      addons:
        pkg:
          - hs-pandoc

compiler: gcc

before_scripts:
  cd src

script:
- if [ "$TRAVIS_OS_NAME" = "freebsd" ]; then gmake; fi
- if [ "$TRAVIS_OS_NAME" != "freebsd" ]; then make; fi
- if [ "$TRAVIS_OS_NAME" = "freebsd" ]; then gmake test; fi
- if [ "$TRAVIS_OS_NAME" != "freebsd" ]; then make test; fi
