.\" Manpage for csg
.\" Contact baxtiarovartem@gmail.com to correct errors
.TH man 1 "July 2021" "0.2"
.SH NAME
csg \- static sites generator written in c
.SH SYNOPSIS
csg src dst
.SH DESCRIPTION
Csg is a very simple static sites generator, it converts files from Markdown to HTML from 
.B src
directory and puts result to 
.B dst 
directory.
.PP
It also generates main page for your site (default index.html) and puts it to the dst directory.
.SH OPTIONS
Csg does not take any options.
.SH FILES
You can find default and system wide csg files under /etc/csg and user csg files under ~/.csg.
.TP 15
/etc/csg/css/pandoc.css 
.B Default
stylesheet for pandoc.
.TP
~/.csg/css/pandoc.css 
.B User
stylesheet for pandoc.
.TP
/etc/csg/css/index.css
.B Default
stylesheet for the main page. 
.TP
~/.csg/css/index.css
.B User
stylesheet for the main page. 
.TP
/etc/csg/html/main_page_header.html
.B Default
main page header.
.TP
~/.csg/html/main_page_header.html
.B User
main page header.
.TP
/etc/csg/html/main_page_footer.html
.B Default
main page footer.
.TP
~/.csg/html/main_page_footer.html
.B User
main page footer.
.TP
/etc/csg/html/main_page_footer.html
.B Default
main page footer.
.TP
~/.csg/html/main_page_footer.html
.B User
main page footer.
.TP
/etc/csg/html/header.html
.B Default
header for the HTML files converted from Markdown with pandoc.
.TP
~/.csg/html/header.html
.B User
header for the HTML files converted from Markdown with pandoc.
.TP
/etc/csg/html/footer.html
.B Default
footer for the HTML files converted from Markdown with pandoc.
.TP
~/.csg/html/footer.html
.B User
footer for the HTML files converted from Markdown with pandoc.
.TP
/etc/csg/html/template.html
.B Default
template for pandoc.
.TP
~/.csg/html/template.html
.B User
template for pandoc.
.SH SEE ALSO
pandoc(1)
.SH AUTHOR
Artem Baxtiarov (baxtiarovartem@gmail.com)
